import { Song } from './types';

export const MOCK_SONGS: Song[] = [
    {
        id: 'K4DyBUG242c',
        title: 'On & On',
        artist: 'Cartoon, Daniel Levi',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/K4DyBUG242c/maxresdefault.jpg',
        duration: '3:28',
        durationSec: 208,
    },
    {
        id: 'bM7SZ5SBzyY',
        title: 'Fade',
        artist: 'Alan Walker',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/bM7SZ5SBzyY/maxresdefault.jpg',
        duration: '4:20',
        durationSec: 260,
    },
    {
        id: 'yJg-Y5byMMw',
        title: 'Mortals',
        artist: 'Warriyo, Laura Brehm',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/yJg-Y5byMMw/maxresdefault.jpg',
        duration: '3:50',
        durationSec: 230,
    },
    {
        id: 'AOeY-nDp7hI',
        title: 'Spectre',
        artist: 'Alan Walker',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/AOeY-nDp7hI/maxresdefault.jpg',
        duration: '3:50',
        durationSec: 230,
    },
    {
        id: 'p7ZsBPK656s',
        title: 'My Heart',
        artist: 'Different Heaven, EH!DE',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/p7ZsBPK656s/maxresdefault.jpg',
        duration: '4:27',
        durationSec: 267,
    },
    {
        id: 'TW9d8vYrVFQ',
        title: 'Invincible',
        artist: 'DEAF KEV',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/TW9d8vYrVFQ/maxresdefault.jpg',
        duration: '4:33',
        durationSec: 273,
    },
    {
        id: 'J2X5mJ3HDYE',
        title: 'Blank',
        artist: 'Disfigure',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/J2X5mJ3HDYE/maxresdefault.jpg',
        duration: '3:29',
        durationSec: 209,
    },
    {
        id: 'f2xGxd9xPYA',
        title: 'Sky High',
        artist: 'Elektronomia',
        album: 'NCS Release',
        coverUrl: 'https://i.ytimg.com/vi/f2xGxd9xPYA/maxresdefault.jpg',
        duration: '3:58',
        durationSec: 238,
    },
];